### ISSUE TITLE
无网络状态下发送命令崩溃

### ISSUE THREAD

**Issue by Asyncz** [cm-heclouds/AndroidSDK#13]
E/chenglei: retried 1 times
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.wiseworld.simple, PID: 11643
    java.util.NoSuchElementException
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:75)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:107)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:87)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.chinamobile.iot.onenet.http.RetryInterceptor.process(RetryInterceptor.java:32)
        at com.chinamobile.iot.onenet.http.RetryInterceptor.process(RetryInterceptor.java:44)
        at com.chinamobile.iot.onenet.http.RetryInterceptor.intercept(RetryInterceptor.java:25)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.chinamobile.iot.onenet.OneNetApi$1.intercept(OneNetApi.java:118)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

**Comment by chenglei1986** [comment]
@Asyncz 这是OkHttp 3.14.0 的bug [https://github.com/square/okhttp/issues/4875](https://github.com/square/okhttp/issues/4875)

**Comment by chenglei1986** [comment]
已对 OkHttp 做降级处理
