### ISSUE TITLE
demo运行不了

### ISSUE THREAD

**Issue by yushengfangzhu** [cm-heclouds/AndroidSDK#15]
demo运行不了，手机魅族魅蓝5s 
Process: com.chinamobile.iot.onenet.sdksample, PID: 30332
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
        at android.widget.Editor.updateCursorPositionMz(Editor.java:6986)
        at android.widget.Editor.updateCursorsPositions(Editor.java:1766)
        at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5703)
        at android.widget.TextView.onDraw(TextView.java:5896)
        at android.view.View.draw(View.java:16539)
        at android.view.View.updateDisplayListIfDirty(View.java:15492)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15484)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.draw(View.java:16551)
        at android.support.design.widget.TextInputLayout.draw(TextInputLayout.java:1577)
        at android.view.View.updateDisplayListIfDirty(View.java:15492)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15484)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15484)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15484)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15484)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at android.view.View.updateDisplayListIfDirty(View.java:15484)
        at android.view.View.draw(View.java:16293)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2839)
        at android.view.View.draw(View.java:16551)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2820)
        at android.view.View.updateDisplayListIfDirty(View.java:15492)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3056)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2860)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2469)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1342)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6824)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
        at android.view.Choreographer.doCallbacks(Choreographer.java:698)
        at android.view.Choreographer.doFrame(Choreographer.java:633)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:882)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6009)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)

**Comment by chenglei1986** [comment]
尝试升级下 SDK 和 com.android.support 库的版本
